### ISSUE TITLE
Issue found on cybereason/src/cybereason/parse /server.py

### ISSUE THREAD

**Issue by githraj** [forensic-security/cybereason#2]
In the log2 method, there is no handling of exceptions that might occur while parsing log entries. If there are malformed or unexpected log entries in the log files, it could lead to unhandled exceptions, causing the parsing process to fail and potentially crashing the entire log parsing script.
def log2(self, buffer, logtype):
    yield from self._log(self.pattern_2, buffer, logtype)

**Comment by nuno-andre** [comment]
Hi @githraj!

Have you found such log entries? Could you please provide Cybereason version and some samples?
